[tool.uv]
constraint-dependencies = ['onnxruntime<1.20.0; python_version == "3.9"']

[tool.uv.sources]
wizzpert-agents = { workspace = true }
wizzpert-plugins-anthropic = { workspace = true }
wizzpert-plugins-assemblyai = { workspace = true }
wizzpert-plugins-aws = { workspace = true }
wizzpert-plugins-azure = { workspace = true }
wizzpert-plugins-cartesia = { workspace = true }
wizzpert-plugins-clova = { workspace = true }
wizzpert-plugins-deepgram = { workspace = true }
wizzpert-plugins-elevenlabs = { workspace = true }
wizzpert-plugins-fal = { workspace = true }
wizzpert-plugins-google = { workspace = true }
wizzpert-plugins-nltk = { workspace = true }
wizzpert-plugins-openai = { workspace = true }
wizzpert-plugins-rime = { workspace = true }
wizzpert-plugins-silero = { workspace = true }
wizzpert-plugins-speechmatics = { workspace = true }
wizzpert-plugins-turn-detector = { workspace = true }
wizzpert-plugins-neuphonic = { workspace = true }
wizzpert-plugins-playai = { workspace = true }
wizzpert-plugins-groq = { workspace = true }
wizzpert-plugins-gladia = { workspace = true }
wizzpert-plugins-resemble = { workspace = true }
wizzpert-plugins-bey = { workspace = true }
wizzpert-plugins-bithuman = { workspace = true }
wizzpert-plugins-speechify = { workspace = true }
wizzpert-plugins-tavus = { workspace = true }
wizzpert-plugins-hume = { workspace = true }

[tool.uv.workspace]
members = ["wizzpert-plugins/*", "wizzpert-agents"]
exclude = ["wizzpert-plugins/wizzpert-plugins-browser"]

[dependency-groups]
dev = [
    "python-dotenv>=1.0.1",
    "mypy",
    "pytest",
    "ruff",
    "pytest-asyncio>=0.25.3",
    "jiwer>=3.1.0",
]

[tool.ruff]
line-length = 100
target-version = "py39"
exclude = [".github"]

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4", # flake8-comprehensions
    "UP", # pyupgrade
]

[tool.ruff.lint.isort]
combine-as-imports = true
known-first-party = ["wizzpert"]

[tool.ruff.lint.pydocstyle]
convention = "google"


[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
addopts = ["--import-mode=importlib", "--ignore=examples"]


[tool.mypy]
strict = true

[tool.mypy-google.genai]
follow_imports = "normal"
follow_untyped_imports = true

[tool.mypy-aiobotocore]
follow_untyped_imports = true

[tool.mypy-boto3]
follow_untyped_imports = true
